# Generated by Django 4.0.1 on 2022-04-07 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('fname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('people', models.IntegerField()),
                ('tdate', models.DateField()),
                ('bookingName', models.CharField(default='', max_length=50)),
                ('bookingFair', models.IntegerField(default=0)),
                ('type', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotelId', models.IntegerField(primary_key=True, serialize=False)),
                ('hotelName', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('hotelAddress', models.TextField()),
                ('pinCode', models.IntegerField()),
                ('hotelDesc', models.TextField()),
                ('roomType', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('image', models.CharField(default='hotel1.webp', max_length=50)),
                ('bType', models.BooleanField(default=0)),
                ('status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='available', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('tourId', models.IntegerField(primary_key=True, serialize=False)),
                ('packageTitle', models.CharField(max_length=100)),
                ('bType', models.BooleanField(default=1)),
                ('type', models.CharField(choices=[('adventure', 'Adventure'), ('wildlife', 'Wildlife'), ('pilgrimage', 'Pilgrimage'), ('family', 'Family'), ('honeymoon', 'Honeymoon')], default='adventure', max_length=32)),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
                ('packageDesc', models.TextField()),
                ('duration', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(default='tour.jpg', max_length=50)),
                ('address', models.TextField(null=True)),
                ('dob', models.DateField(null=True)),
                ('contact', models.IntegerField(null=True)),
                ('userI', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Hotels',
        ),
    ]
