# Generated by Django 4.0.1 on 2022-03-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_package_rename_hotels_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='image',
        ),
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.CharField(default='hotel1.webp', max_length=50),
        ),
        migrations.AddField(
            model_name='package',
            name='image1',
            field=models.CharField(default='tour.jpg', max_length=50),
        ),
        migrations.AddField(
            model_name='package',
            name='image2',
            field=models.CharField(default='tour.jpg', max_length=50),
        ),
    ]
