# Generated by Django 4.0.1 on 2022-04-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_package_image_hotel_image_package_image1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userc',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=100)),
                ('emailid', models.EmailField(max_length=254)),
                ('image', models.CharField(default='tour.jpg', max_length=50)),
                ('pswd', models.CharField(max_length=20)),
                ('cpswd', models.CharField(max_length=20)),
                ('address', models.TextField(null=True)),
                ('dob', models.DateField(null=True)),
                ('contact', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('adventure', 'Adventure'), ('wildlife', 'Wildlife'), ('pilgrimage', 'Pilgrimage'), ('family', 'Family'), ('honeymoon', 'Honeymoon')], default='adventure', max_length=32),
        ),
    ]
