# Generated by Django 4.0.1 on 2022-04-02 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_userdata_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='contact',
            field=models.IntegerField(null=True),
        ),
    ]
