# Generated by Django 4.0.1 on 2022-04-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bookingFair',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='bookingName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
