# Generated by Django 4.0.1 on 2022-04-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_booking_bookingfair_booking_bookingname'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(default='tour.jpg', max_length=50)),
                ('address', models.TextField(null=True)),
                ('dob', models.DateField(null=True)),
                ('contact', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Userdata',
        ),
    ]
