# Generated by Django 4.0.1 on 2022-04-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_userdata_useri'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='bType',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='bType',
            field=models.BooleanField(default=1),
        ),
    ]
