# Generated by Django 4.0.1 on 2022-04-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_hotel_btype_package_btype'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='type',
            field=models.BooleanField(default=0),
        ),
    ]
