# Generated by Django 4.0.1 on 2022-04-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_booking_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='image1',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='package',
            name='image2',
            field=models.ImageField(upload_to=''),
        ),
    ]
