# Generated by Django 4.0.1 on 2022-04-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_booking_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='disPrice',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='discount',
            field=models.BooleanField(null=True),
        ),
    ]
