# Generated by Django 4.0.1 on 2022-04-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_package_image1_alter_package_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='image1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='package',
            name='image2',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
