# Generated by Django 4.0.1 on 2022-04-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_package_image1_alter_package_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='disPrice',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='discount',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='image1',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='package',
            name='image2',
            field=models.ImageField(upload_to=''),
        ),
    ]
