# Generated by Django 4.0.1 on 2022-04-07 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_booking_hotel_package_userdata_delete_hotels'),
        ('main', '0021_remove_package_disprice_remove_package_discount'),
    ]

    operations = [
    ]
